In [9]:
# Notebook: State-Space Representation from Differential Equation
# Author: Adapted for Springer-style presentation
# Language: English

import numpy as np

# ==========================
# Differential Equation
# ==========================
# y''' - 5 y'' + 2 y' + 4 y = 3 x' - 4 x
# Coefficients of output side (left-hand side): a0 y + a1 y' + a2 y'' + a3 y''' = ...
alpha = np.array([4.0, 2.0, -5.0, 1.0])   # a0, a1, a2, a3 (a3 = 1 – normalized)
beta  = np.array([-4.0, 3.0, 0.0, 0.0])   # b0, b1, b2, b3

N = 3   # system order
M = 1   # input derivative order (highest is x')

print("Differential Equation:")
print("y''' - 5 y'' + 2 y' + 4 y = 3 x' - 4 x")
print("The system is given in normalized form (leading coefficient a3 = 1)\n")

# ───────────────────────────────────────────────
# Direct Form II – Controllable Canonical Form
# ───────────────────────────────────────────────
A_df2 = np.array([
    [0,               1,               0              ],
    [0,               0,               1              ],
    [-alpha[0]/alpha[3], -alpha[1]/alpha[3], -alpha[2]/alpha[3]]
])

B_df2 = np.array([[0.0],
                  [0.0],
                  [1.0 / alpha[3]]])

# Feedthrough terms for output equation
C_df2 = np.array([[beta[0] - beta[3]*alpha[0]/alpha[3],
                   beta[1] - beta[3]*alpha[1]/alpha[3],
                   beta[2] - beta[3]*alpha[2]/alpha[3]]])

D_df2 = np.array([[beta[3] / alpha[3]]])   # usually 0 in this example

print("=== Direct Form II (Controllable Canonical Form) ===")
print("A =\n", np.round(A_df2, 3))
print("B =\n", B_df2)
print("C =\n", np.round(C_df2, 3))
print("D =\n", D_df2)

# Scalar state equations – Direct Form II
print("\nScalar state equations (Direct Form II):")
for i in range(N-1):
    print(f"  dq{i+1}/dt = q{i+2}")

last_eq_terms = []
for j in range(N):
    coeff = -alpha[j] / alpha[3]
    if coeff != 0:
        last_eq_terms.append(f"{coeff:+.1f} q{j+1}")
last_eq = " + ".join(last_eq_terms).lstrip('+ ') + " + u"
print(f"  dq{N}/dt   = {last_eq}")

# Output equation
y_terms = []
for j in range(N):
    if C_df2[0, j] != 0:
        y_terms.append(f"{C_df2[0,j]:+.1f} q{j+1}")
y_str = " + ".join(y_terms).lstrip('+ ')
if D_df2[0,0] != 0:
    y_str += f" + {D_df2[0,0]:+.1f} u"
print("  y         = " + (y_str if y_str else "0") + "\n")


# ───────────────────────────────────────────────
# Direct Form I – Observable Canonical Form
# ───────────────────────────────────────────────
A_df1 = np.array([
    [-alpha[2]/alpha[3],  1.0,           0.0         ],
    [-alpha[1]/alpha[3],  0.0,           1.0         ],
    [-alpha[0]/alpha[3],  0.0,           0.0         ]
])

B_df1 = np.array([
    [beta[2] - beta[3] * alpha[2]/alpha[3]],
    [beta[1] - beta[3] * alpha[1]/alpha[3]],
    [beta[0] - beta[3] * alpha[0]/alpha[3]]
])

C_df1 = np.array([[1.0, 0.0, 0.0]])
D_df1 = np.array([[beta[3] / alpha[3]]])   # usually 0

print("=== Direct Form I (Observable Canonical Form) ===")
print("A =\n", np.round(A_df1, 3))
print("B =\n", np.round(B_df1, 3))
print("C =\n", C_df1)
print("D =\n", D_df1)

# Scalar state equations – Direct Form I
print("\nScalar state equations (Direct Form I):")
for i in range(N):
    row_terms = []
    for j in range(N):
        coeff = A_df1[i, j]
        if coeff != 0:
            row_terms.append(f"{coeff:+.1f} q{j+1}")
    if B_df1[i, 0] != 0:
        row_terms.append(f"{B_df1[i,0]:+.1f} u")
    
    eq = " + ".join(row_terms).lstrip('+ ')
    print(f"  dq{i+1}/dt = {eq if eq else '0'}")

# Output equation
y_terms = []
for j in range(N):
    if C_df1[0, j] != 0:
        y_terms.append(f"{C_df1[0,j]:+.1f} q{j+1}")
y_str = " + ".join(y_terms).lstrip('+ ')
if D_df1[0,0] != 0:
    y_str += f" + {D_df1[0,0]:+.1f} u"
print("  y         = " + (y_str if y_str else "0"))


print("\nEnd of state-space realizations.")

Differential Equation:
y''' - 5 y'' + 2 y' + 4 y = 3 x' - 4 x
The system is given in normalized form (leading coefficient a3 = 1)

=== Direct Form II (Controllable Canonical Form) ===
A =
 [[ 0.  1.  0.]
 [ 0.  0.  1.]
 [-4. -2.  5.]]
B =
 [[0.]
 [0.]
 [1.]]
C =
 [[-4.  3.  0.]]
D =
 [[0.]]

Scalar state equations (Direct Form II):
  dq1/dt = q2
  dq2/dt = q3
  dq3/dt   = -4.0 q1 + -2.0 q2 + +5.0 q3 + u
  y         = -4.0 q1 + +3.0 q2

=== Direct Form I (Observable Canonical Form) ===
A =
 [[ 5.  1.  0.]
 [-2.  0.  1.]
 [-4.  0.  0.]]
B =
 [[ 0.]
 [ 3.]
 [-4.]]
C =
 [[1. 0. 0.]]
D =
 [[0.]]

Scalar state equations (Direct Form I):
  dq1/dt = 5.0 q1 + +1.0 q2
  dq2/dt = -2.0 q1 + +1.0 q3 + +3.0 u
  dq3/dt = -4.0 q1 + -4.0 u
  y         = 1.0 q1

End of state-space realizations.
